version: "3"

services:
  nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ./nginx-configuration-file:/etc/nginx/conf.d/default.conf
      -  ./static:/home/www-data/groupXX/static
      -  ./media:/home/www-data/groupXX/media

  sec:
    build: .
    image: sec
    network_mode: "host"
    volumes:
      - ./sec:/usr/src/app/sec
      - ./static:/usr/src/app/sec/static
      - ./media:/usr/src/app/sec/media
